casgate/casgate

controllers/ldap.go
object/ldap_autosync.go

Make some improvements for LDAP work:
* update ldap sync time after synchronization is finished, not before
* when ldap autosync is enabled, first synchronization will be straightaway after adding/updating ldap settings, not after first timeout

Ldap improvements

---

object/user.go

now policy mapper is called on every user login because last_signin_time updated. It is redundant.

fix: update user policy only if groups,name, owner updated

---

controllers/ldap.go

removed redundant check for ldap server name in test-ldap route

fix: removed redundant checks in /test-ldap

---

object/migrator_1_198_0_PR_56.go

This commit addresses an issue in the migration check condition of Migrator_1_198_0_PR_56. Previously, the condition used the logical OR operator instead of the logical AND operator, causing the migration to not be applied correctly. The correct condition now ensures that the migration is only applied when the database type is either POSTGRES or MYSQL

fix: Correct migration condition in Migrator_1_198_0_PR_56

---

object/migrator_1_287_0_PR_62.go

Added a check to ensure the presence of the 'password_change_required' field in the user table structure. In a clean database scenario, this field may not exist initially, as it was not included in the description of the object.User structure. Originally, the field appeared in the table due to being added in the User structure description, causing xorm to include it in the table. However, in the new code, this field is no longer present in the structure. Nonetheless, a migration is applied that attempts to remove it, leading to a panic in the code.

fix: add migration check for presence of 'password_change_required' column

---

object/cert.go

this change fixes creation of certificates from api
before the change there was an error when trying to add ca certificate scoped cert with bitsize 0 and empty privateKey, this leaded to panic in cert.go AddCert method (the cause of the panic is zero given as bitSize parameter to the generateRsaKeys func)

feat: generating keys only for jwt certificate scope

---

object/check_username_test.go
util/validation.go

Add use of special symbols in username
List of special symbols: ```!#$%&'*+/=?^`{|}~@.```
Symbol are allowed in the middle of name along with underscores and hyphens. 
Start and finish symbol of the username must be alphanumeric.

feat: extend allowed symbols for username

---

controllers/ldap.go
object/ldap.go

in the `api/test-ldap` endpoint, if the password is `***`, added taking the password from the ldap server stored in the database

fix: added getting a password when testing ldap if ldap exists in the db

---

web/package.json
web/yarn.lock

Bumps nth-check from 1.3.2 to 2.1.1 via updating css-select and svgo

build(deps): bump nth-check from 1.3.2 to 2.1.1 in /web

---

web/package.json
web/yarn.lock

Bumps @cypress/request from to 3.0.1 in /web
Also, bumps tough-cookie from 2.5.0 to >=4.1.3 in /web

build(deps): bump @cypress/request from 2.88.11 to 3.0.1 in /web

---

object/saml_idp.go

replaced the use of sha-1 with sha-256 in object.GetSamlResponse()

fix: update sha-1 to sha-256 in GetSamlResponse func

---

web/src/Setting.js
web/src/auth/ProviderButton.js
web/src/common/modal/AgreementModal.js

These functions are vulnerable to DOM XSS if an attacker uses alternative protocols (javascript://, data://).
For ProviderButton.js the fix is ​​target blank since it is already used in another Provider function.
For goToLink, which is used in post-payment returns where XSS is present, and TermOfUse the fix is ​​the http protocol predicate.

Fix 3 DOM XSS issues

---

controllers/ldap.go
object/check.go
object/ldap_autosync.go
object/ldap_conn.go
object/policy_mapper_test.go

Previously, deletion requests for LDAP configurations with a non-zero Auto Sync time frequently hung indefinitely. In the current fix, cancellation of LDAP connection attempts on deletion of LDAP servers has been added, which ensures that hanging deletion requests are avoided

fix: add cancellation of LDAP connection on deletion of LDAP server

---

object/record_builder.go

Added retrieval of RecordBuilder using the initialization function NewRecordBuilder to prevent panic. Previously, a panic occurred in the AddReason function when the record was not initialized
```
/usr/local/go/src/runtime/panic.go:261
/usr/local/go/src/runtime/signal_unix.go:861
/go/src/casgate/object/record_builder.go:85
/go/src/casgate/object/application.go:212
/go/src/casgate/object/application.go:368
/go/src/casgate/object/token.go:256
/go/src/casgate/object/token.go:293
/go/src/casgate/controllers/auth.go:150
/go/src/casgate/controllers/auth.go:543
/usr/local/go/src/reflect/value.go:596
/usr/local/go/src/reflect/value.go:380
/go/pkg/mod/github.com/beego/beego@v1.12.12/router.go:897
/usr/local/go/src/net/http/server.go:2938
/usr/local/go/src/net/http/server.go:2009 …
```

fix: add recordBuilder via init func

---

controllers/auth.go

Added a fix for an issue where logging in through a provider could cause a panic if the provider was not associated with the admin organization

fix: handle provider lookup for non-admin orgs during login

---

.gitignore
controllers/auth.go
object/ldap.go
object/ldap_attribute_mapping.go
object/ldap_conn.go
object/ldap_role_mapping.go
object/user_util.go
web/src/LdapEditPage.js
web/src/locales/ru/data.json

add checkbox to enable case-insensitivity
if this checkbox is true:
- attributes and roles are mapped **regardless of the input case**
- during the login via ldap, if we could not find such a login in the database, but we received a username from the AD server, but in a different register, then this **new username is replaced instead of the old one** for further login flow
more info in `ASP-514`

feat: case insensitivity handling

---

controllers/account.go

Fixed the issue where a new user registering via invitation would be assigned an unhashed password if a password hashing algorithm was specified. Now, the password is hashed correctly

fix: resolve registration via invitation with unhashed password

---

web/src/theme.js

Tooltips are made more readable.
Before:
After:

fix: update tooltip text color

---

ldap_sync/connection.go
object/check.go

When searching for a user in AD, you need to take into account that the field names differ from the usual LDAP server.

ldap search filter fix

---

controllers/account.go
controllers/casbin_api.go
controllers/ldap.go
controllers/user.go
object/adapter.go
object/application.go
object/cert.go
object/check.go
object/domain.go
object/enforcer.go
object/group.go
object/init.go
object/migrator_1_240_0_PR_1539.go
object/model.go
object/organization.go
object/permission.go
object/provider.go
object/radius.go
object/resource.go
object/role.go
object/session.go
object/token.go
object/user.go
object/user_enforcer.go
object/webhook.go
routers/auto_signin_filter.go
routers/record.go
routers/static_filter.go
util/string.go

fix: rename method for clarity
Moved application detection higher up
Renamed method, added const usage 
resulting log message
```{"dt":"2024-09-02 14:38:26.304","lvl":"INFO","msg":"","obj":"admin/admin-ui-app","ip":"::1: ","obj-type":"application","usr":"PT/fry","act":"logout","r":"success"}```

fix: log correct org name

---

controllers/ldap.go
ldap_sync/connection.go

chore: some renaming for clarity
fix: remove invalid usage of go-ldap lib api, that caused panic
ASP-1304
Same issue as https://github.com/go-ldap/ldap/issues/363

fix: remove invalid usage of go-ldap lib api, that caused panic

---

controllers/ldap.go
ldap_sync/connection.go

There are 2 ways to connect to ldap - 1) with username and password 2) with certificates
Validation now does not require password in second case.
Bind() call removed, because it is done within GetLdapConn already
Some renaming.

fix: test ldap connection validation

---

object/domain.go
object/group.go
object/permission.go
object/role.go
object/user.go

> SQL defines two primary character types: character varying(n) and character(n), where n is a positive integer. Both of these types can store strings up to n characters (not bytes) in length
https://www.postgresql.org/docs/current/datatype-character.html

fix: check for characters instead of bytes in casbin policy values
