cred/argon2id.go, cred/bcrypt.go, cred/manager.go, cred/md5-user-salt.go, cred/pbkdf2-salt.go, cred/plain.go, cred/sha256-salt.go, cred/sha256-salt_test.go, object/check.go, object/migrator.go, object/migrator_1_336_0_PR_1970.go, object/organization.go, object/user_cred.go, object/user_cred_test.go, object/user_util.go
fix #8 Stop using static salt to hash passwords and start using dynamic one
=> fix: fixes #8 dynamic salt

object/session.go
fixes error while deleting user:
{
"status": "error",
"msg": "sql: converting argument $3 type: unsupported type object.Application, a struct",
"sub": "",
"name": "",
"data": null,
"data2": null
}
=> feat: session delete fix

controllers/auth.go, object/saml_sp.go, object/user.go, object/user_util.go
add signup/link user for saml providers.
=> feat: signup for saml providers

object/policy_builder_util.go
fix possible panic in getAncestorEntitiesById
=> fix: fix possible panic in getAncestorEntitiesById

controllers/account.go, object/record.go, routers/record.go, web/src/RecordListPage.js, web/src/WebhookEditPage.js
- add body for Record to record table (mask password, clientSecret, apikey, otp)
- add status code for Record to record table and webhooks
- add userInfo for logout
=> feat: add status code and object to record. add userInfo for logout.

controllers/domain.go, main.go, object/domain.go, object/ormer.go, object/policy_builder.go, object/policy_builder_util.go, object/policy_mapper.go, object/repository.go, repository/domain.go, repository/group.go, repository/model.go, repository/permission.go, repository/repository.go, repository/role.go, repository/user.go, txmanager/context.go, txmanager/txmanager.go
- add repository layer and transaction manager.
- policy difference now processing in transaction with lock by model. 
- object.GetDomains demonstrates using repo without transaction.
=> feat: add repository and transaction manager

init_data.json.template, object/init.go, web/src/OrganizationListPage.js
fix: https://github.com/casgate/casgate/issues/14
=> fix: argon2id as default

controllers/auth.go, idp/provider.go, idp/vk.go
fix: https://github.com/casgate/casgate/issues/35
=> feat: add vk support

routers/router.go
fixed api/test-openid to api/test-provider
=> routing hotfix

object/application.go, web/src/ApplicationEditPage.js, web/src/basic/AppListPage.js, web/src/locales/ar/data.json, web/src/locales/de/data.json, web/src/locales/en/data.json, web/src/locales/es/data.json, web/src/locales/fa/data.json, web/src/locales/fi/data.json, web/src/locales/fr/data.json, web/src/locales/he/data.json, web/src/locales/id/data.json, web/src/locales/it/data.json, web/src/locales/ja/data.json, web/src/locales/kk/data.json, web/src/locales/ko/data.json, web/src/locales/ms/data.json, web/src/locales/nl/data.json, web/src/locales/pl/data.json, web/src/locales/pt/data.json, web/src/locales/ru/data.json, web/src/locales/sv/data.json, web/src/locales/tr/data.json, web/src/locales/uk/data.json, web/src/locales/vi/data.json, web/src/locales/zh/data.json
only public applications are shown at /apps page
=> feat: add isPublic flag for applications

controllers/auth.go, controllers/base.go, object/token.go, object/token_jwt.go, routers/base.go, routers/static_filter.go, util/string.go
added sid claim to tokens as sha256 from username and sessionId
=> feat: added sid claim to tokens

i18n/locales/ar/data.json, i18n/locales/de/data.json, i18n/locales/en/data.json, i18n/locales/es/data.json, i18n/locales/fa/data.json, i18n/locales/fi/data.json, i18n/locales/fr/data.json, i18n/locales/he/data.json, i18n/locales/id/data.json, i18n/locales/it/data.json, i18n/locales/ja/data.json, i18n/locales/kk/data.json, i18n/locales/ko/data.json, i18n/locales/ms/data.json, i18n/locales/nl/data.json, i18n/locales/pl/data.json, i18n/locales/pt/data.json, i18n/locales/ru/data.json, i18n/locales/sv/data.json, i18n/locales/tr/data.json, i18n/locales/uk/data.json, i18n/locales/vi/data.json, i18n/locales/zh/data.json, object/check.go
Enhance the login error message handling for improved security. When attempting to log in with an incorrect username, the error message no longer discloses information about the non-existence of the user. Instead, a more generalized error message is displayed: 'Invalid username or password.'
=> fix: improve login error message handling

object/oidc_discovery.go, util/path.go
fix getOriginFromHost logic to return origin from host for request via non-conf host.
=> feat: fix getOriginFromHost logic

controllers/user.go, controllers/util.go
Set HTTP 400 Bad Request status when CheckPasswordSame encounters an error
=> fix: return bad request when trying to change pwd on current

object/ldap.go
fixed update ldap CA certificate field
=> fix: ldap cert update

routers/record.go
fix: [84](https://github.com/casgate/casgate/issues/84)
=> fix: remove overvrite record detail

controllers/auth.go, idp/oidc.go, idp/provider.go, object/application.go, object/migrator_1_287_0_PR_62.go, object/provider.go, object/user.go, web/src/ProviderEditPage.js, web/src/Setting.js, web/src/auth/Provider.js
add openid provider with configuration link support
=> feat: oidc provider type

controllers/ldap.go, object/ldap_autosync.go, object/record_builder.go, routers/record.go
Added record messages to background job for LDAP user sync
=> feat: Added record messages to LDAP autosync

controllers/provider.go, controllers/saml.go, web/src/ProviderEditPage.js, web/src/Setting.js, web/src/locales/ar/data.json, web/src/locales/de/data.json, web/src/locales/en/data.json, web/src/locales/es/data.json, web/src/locales/fa/data.json, web/src/locales/fi/data.json, web/src/locales/fr/data.json, web/src/locales/he/data.json, web/src/locales/id/data.json, web/src/locales/it/data.json, web/src/locales/ja/data.json, web/src/locales/kk/data.json, web/src/locales/ko/data.json, web/src/locales/ms/data.json, web/src/locales/nl/data.json, web/src/locales/pl/data.json, web/src/locales/pt/data.json, web/src/locales/ru/data.json, web/src/locales/sv/data.json, web/src/locales/tr/data.json, web/src/locales/uk/data.json, web/src/locales/vi/data.json, web/src/locales/zh/data.json
- Added NameIDFormat to saml methadata
- Fix extracting saml methadata with prefixed xml
- Hide some fields on edit provider form if type not Generic
- Rename Custom to Generic saml type for compatibility purpose
- Added translations
- Some code reorganization
=> feat: added fields to saml methadata

authz/authz.go, controllers/auth.go, controllers/ldap.go, form/auth.go, object/ldap_conn.go, routers/router.go, web/src/auth/LoginPage.js, web/src/backend/LdapBackend.js, web/src/common/select/LdapSelect.js, web/src/locales/en/data.json, web/src/locales/ru/data.json
- Add dropdown with Ldap servers to login page
- Login user only via selected ldap server
=> feat: select ldap server via login

controllers/cert.go, controllers/ldap.go, object/ldap_conn.go, object/provider.go, swagger/swagger.json, swagger/swagger.yml
- Certificate cannot be deleted if linked with provider
=> fix: cert cannot be deleted if linked with provider

controllers/cert.go
=> fix: remove unused import

controllers/auth.go, object/syncer_util.go, routers/authz_filter.go
- Stop handler execution if error appear
=> fix: stop handler execution if error

object/user.go, web/src/ProviderEditPage.js, web/src/Setting.js
- Generic SAML provider login error
=> fix: Generic SAML provider login error

controllers/auth.go
- Hide error messages with inner implementations
=> feat: hide error messages with inner implementations

controllers/auth.go
- API response without extra json information
=> fix: api response without json information

controllers/auth.go, controllers/saml.go, object/provider.go, object/saml_sp.go, web/src/ProviderEditPage.js, web/src/locales/ar/data.json, web/src/locales/de/data.json, web/src/locales/en/data.json, web/src/locales/es/data.json, web/src/locales/fa/data.json, web/src/locales/fi/data.json, web/src/locales/fr/data.json, web/src/locales/he/data.json, web/src/locales/id/data.json, web/src/locales/it/data.json, web/src/locales/ja/data.json, web/src/locales/kk/data.json, web/src/locales/ko/data.json, web/src/locales/ms/data.json, web/src/locales/nl/data.json, web/src/locales/pl/data.json, web/src/locales/pt/data.json, web/src/locales/ru/data.json, web/src/locales/sv/data.json, web/src/locales/tr/data.json, web/src/locales/uk/data.json, web/src/locales/vi/data.json, web/src/locales/zh/data.json
- Added proper signature description
- Added more valid time for methadata
- Fix extract SAML urls from methadata
- etc
=> feat: improve generic saml provider

controllers/auth.go, controllers/saml.go
=> feat: fix path generation

routers/cors_filter.go
- Added logging for CORS errors
=> feat: Added logging for CORS errors

object/oidc_discovery.go, object/saml_sp.go
- Get origin from host with config priority
=> feat: Get origin from host with config priority

controllers/auth.go, util/slice.go
- Forcibly change password if wrong login
=> fix: forcibly change password if wrong login

controllers/user_api_tokens.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml
- Rename AccessToken to ApiToken
=> feat: rename AccessToken to ApiToken

routers/record.go
added a function sanitizeData that masks the fields specified in the slice sensitiveResponseFields to "***"
=> fix: hide sensitive fields from record.response

routers/record.go
moved sensitive fields and string to replace to parameter
=> fix: made sanitizeData() reusable

controllers/record.go, main.go, object/record.go, routers/cors_filter.go
- Added logs to record 
- Record bad CORS requests
=> feat: added logs to record and record bad CORS requests

object/saml_sp.go, role_mapper/saml_mapper.go
- Extract all roles in metadata
=> fix: extract all roles in methadata

controllers/user.go
=> fix: strip slashes

object/group.go, object/user.go, routers/static_filter.go
Fix security issues
SQL Injection(admin permissions)
Path traversal(when deploy without reverse proxy like nginx)
=> Fix security issues

web/package.json, web/yarn.lock
=> build(deps): bump postcss from 7.0.39 to 8.4.31 in /web

web/package.json, web/yarn.lock
=> build(deps): bump crypto-es from 1.2.7 to 2.1.0 in /web

controllers/auth.go
- Change error to unauthorized
=> feat: change error to unauthorized

main.go, object/record_builder.go
- Change error description 
- Move up set record filer
=> fix: change error description & move up set record filer

object/check.go
added a check whether the user is disabled on the ldap server using the `data` value in the error line
=> fix: added check whether user is disabled on ldap server

controllers/user.go
=> fix: wrong creation email body

controllers/user_api_tokens.go, go.mod, go.sum, object/user_api_token.go, routers/router.go, swagger/swagger.json, swagger/swagger.yml
added the receipt of tokens for a specific user by user_id
_more details in ASP-653_
=> feat: get user tokens

object/check.go, object/check_test.go, object/ldap_util.go, object/ldap_util_test.go, object/policy_mapper_test.go
an error occurred that the value of the userAccountControl attribute is not always equal to 514
so I did a full attribute check and I'm looking for an attribute indicating that the account is blocked
=> feat: add full scan of userAccountControl attribute

swagger/swagger.json, swagger/swagger.yml
little fixes of swagger docs for `Api Token API`
=> fix: update api-token swagger api

controllers/user_api_tokens.go, object/user_api_token.go, object/user_util.go
added validation for emptiness and for the format of the token and user ID
=> feat: add userId and api_token validation

controllers/service.go, web/src/common/TestEmailWidget.js
Fix the error where a panic occurred when attempting to test the SMTP connection with an organization other than Admin
=> fix: add get provider via owner and providerName

controllers/provider.go, idp/oidc.go, object/application.go
=> fix: add http client setting in controller

web/src/common/modal/CaptchaModal.js
=> fix: forbid request to send email with invalid captcha

conf/app.conf, docker-compose.yml
=> feat: add postgres as default db

controllers/account.go, object/user.go, web/src/ApplicationListPage.js, web/src/table/SignupTable.js
=> fix: set only uuid type id for user

controllers/webhook.go
=> feat: validate webhook organization on update

web/src/CertListPage.js
=> fix: remove shared certs as default

web/src/table/LdapTable.js
=> fix: add valid link to edit ldap page

controllers/application.go, controllers/provider.go, object/application.go, object/init.go, object/init_data.go, object/provider.go, object/provider_util.go, object/provider_util_test.go, util/logger/helpers.go, util/logger/types.go
=> feat: add provider logs

controllers/types.go, controllers/user_api_tokens.go, util/logger/types.go
=> feat: add user api token logs

controllers/account.go, controllers/casbin_api.go, controllers/ldap.go, controllers/user.go, object/adapter.go, object/application.go, object/cert.go, object/check.go, object/domain.go, object/enforcer.go, object/group.go, object/model.go, object/organization.go, object/permission.go, object/provider.go, object/radius.go, object/role.go, object/token.go, object/user.go, object/webhook.go, routers/auto_signin_filter.go, routers/base.go, routers/record.go, routers/static_filter.go, util/routine.go, util/string.go, util/time.go
fix: rename panicking methods so that "panic" is in their name
fix: remove dead code
=> fix: use errors instead of panics in a lot of places

controllers/auth.go, controllers/ldap.go, object/ldap_conn.go, object/ldap_role_mapping.go, object/role.go, util/logger/types.go
add logs about changing roles via ldap mapping
_`ASP-1196`_
=> feat: ldap role mapping logs

web/src/common/PasswordChecker.js
=> fix: edit default min pass length rule

orm/ormer_session.go
=> feat: add case-independent orm sessions

controllers/auth.go, controllers/ldap.go, object/ldap_syncronization_manager.go, object/record_builder.go, object/role.go, object/role_test.go
add separated record builder to record events for each user
_more details in `ASP-1227`_
=> feat: record changes during role mapping

controllers/application.go, controllers/domain.go, controllers/group.go, controllers/model.go, controllers/organization.go, controllers/provider.go, controllers/webhook.go, object/application.go, object/base.go, object/domain.go, object/group.go, object/model.go, object/organization.go, object/provider.go, object/webhook.go, web/src/backend/OrganizationBackend.js
also organizationName param in get-organization method renamed to organization
=> Fix: filter without pagination

orm/ormer_session.go
This reverts commit 82e19447218e55a7a68121a6eed02cc359582fe5.
=> Revert "feat: add case-independent orm sessions"

web/src/auth/LoginPage.js, web/src/locales/ar/data.json, web/src/locales/de/data.json, web/src/locales/en/data.json, web/src/locales/es/data.json, web/src/locales/fa/data.json, web/src/locales/fi/data.json, web/src/locales/fr/data.json, web/src/locales/he/data.json, web/src/locales/id/data.json, web/src/locales/it/data.json, web/src/locales/ja/data.json, web/src/locales/kk/data.json, web/src/locales/ko/data.json, web/src/locales/ms/data.json, web/src/locales/nl/data.json, web/src/locales/pl/data.json, web/src/locales/pt/data.json, web/src/locales/ru/data.json, web/src/locales/sv/data.json, web/src/locales/tr/data.json, web/src/locales/uk/data.json, web/src/locales/vi/data.json, web/src/locales/zh/data.json
=> fix: edit ldap login error message

web/src/OrganizationListPage.js, web/src/backend/OrganizationBackend.js
=> fix: org not found with special symbols

controllers/auth.go, object/ldap_conn.go, object/user.go
=> fix: add userID from newUser entity && update context in login handler

controllers/types.go, controllers/user.go, web/src/ProviderEditPage.js
=> feat: add productName as parameter to email invite

controllers/organization.go, object/check.go, object/group.go, util/logger/types.go
also fixed check of linked role/permissions for delete group method
=> fix: empty organization name validation

object/check.go
=> fix: don't sync user.IsForbidden with ldap attr

controllers/auth.go, web/src/auth/AuthBackend.js, web/src/auth/Provider.js
=> fix: correct state forming

controllers/auth.go
=> fix: generate id when signup with idp

object/domain.go, object/group.go, object/permission.go, object/policy_builder_types.go, object/role.go, object/user.go
=> fix: check policy values for length

web/src/auth/ChangePasswordForm.js
=> fix: remove validation mark from old password form

object/domain.go
=> fix: panic if domain doesn't exist in subdomains

.gitignore, controllers/auth.go, idp/oidc.go, idp/provider.go, object/ldap_conn.go, object/user.go, web/src/ProviderEditPage.js
=> feat: add new fields to user attribute mapping

object/saml_sp.go
=> feat: support first name and last name in SAML user mapping 

controllers/auth.go
=> feat: save get-auth-url errors to records
